import 'package:moneko/features/home/presentation/models/models.dart';
import 'package:moneko/features/pockets/domain/entities/pocket_envelope.dart';
import 'package:moneko/features/recurring/domain/models/recurring_transaction.dart';
import 'package:moneko/features/households/domain/entities/household.dart';
import 'package:moneko/features/wallets/domain/entities/wallet.dart';

/// Curated mock content surfaced whenever preview mode is active.
class PreviewMockData {
  static final UserContact contact = UserContact(
    id: 'preview-contact',
    userId: 'preview-user',
    phoneE164: null,
    verified: true,
    preferredCurrency: 'USD',
    preferredTimezone: 'America/Los_Angeles',
  );

  static List<ExpenseEntry> get expenses =>
      _expenses.map((entry) => entry.copyWith()).toList(growable: false);

  static List<DailyBudgetEntry> get budgets =>
      _budgets.map((entry) => entry.copyWith()).toList(growable: false);

  static List<PocketEnvelope> get pockets =>
      _pockets.map(_copyPocket).toList(growable: false);

  static List<RecurringTransaction> get recurringTransactions =>
      _recurringTransactions.map(_copyRecurring).toList(growable: false);

  static List<Household> get households =>
      _households.map(_copyHousehold).toList(growable: false);

  static List<WalletEntity> get wallets =>
      _wallets.map(_copyWallet).toList(growable: false);

  static final List<ExpenseEntry> _expenses = [
    ExpenseEntry(
      id: 'preview-expense-1',
      contactId: contact.id,
      userId: contact.userId,
      userName: 'Casey D.',
      userAvatarUrl: null,
      householdId: null,
      date: DateTime.now().subtract(const Duration(days: 1)),
      amountCents: 2450,
      currency: 'USD',
      category: 'Groceries',
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
      updatedAt: null,
      rawText: 'Weekly farmer market haul',
      breakdown: const ['Veggies', 'Snacks'],
      receiptImageUrl: null,
      sharedMemberIds: const [],
      splitGroupId: null,
      bankAccountId: null,
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-2',
      contactId: contact.id,
      userId: contact.userId,
      userName: 'Casey D.',
      householdId: 'preview-house-1',
      date: DateTime.now().subtract(const Duration(days: 2)),
      amountCents: 1299,
      currency: 'USD',
      category: 'Dining',
      createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 4)),
      rawText: 'Lunch with Sam — Thai Garden',
      breakdown: const [],
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-3',
      contactId: contact.id,
      userId: contact.userId,
      date: DateTime.now().subtract(const Duration(days: 3)),
      amountCents: 5800,
      currency: 'USD',
      category: 'Transportation',
      createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 6)),
      rawText: 'Monthly metro reload',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-4',
      contactId: contact.id,
      userId: contact.userId,
      date: DateTime.now().subtract(const Duration(days: 4)),
      amountCents: 3500,
      currency: 'USD',
      category: 'Wellness',
      createdAt: DateTime.now().subtract(const Duration(days: 4, hours: 3)),
      rawText: 'Yoga studio membership',
      type: 'expense',
      isRecurring: true,
    ),
    ExpenseEntry(
      id: 'preview-expense-5',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-house-2',
      date: DateTime.now().subtract(const Duration(days: 5)),
      amountCents: 18000,
      currency: 'USD',
      category: 'Salary',
      createdAt: DateTime.now().subtract(const Duration(days: 5, hours: 1)),
      rawText: 'Product Design Retainer',
      type: 'income',
      isRecurring: true,
    ),
    ExpenseEntry(
      id: 'preview-expense-6',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-card',
      date: DateTime.now().subtract(const Duration(hours: 12)),
      amountCents: 4200,
      currency: 'USD',
      category: 'Debt Payments',
      createdAt: DateTime.now().subtract(const Duration(hours: 11)),
      rawText: 'Credit card payment — Sapphire',
      type: 'expense',
      isRecurring: true,
    ),
    ExpenseEntry(
      id: 'preview-expense-7',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-card',
      date: DateTime.now().subtract(const Duration(days: 1, hours: 6)),
      amountCents: 1899,
      currency: 'USD',
      category: 'Travel',
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 5)),
      rawText: 'Airport rideshare – business trip',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-8',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-savings',
      date: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
      amountCents: 50000,
      currency: 'USD',
      category: 'Transfers',
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
      rawText: 'Auto-transfer to High-Yield Savings',
      type: 'expense',
      isRecurring: true,
    ),
    ExpenseEntry(
      id: 'preview-expense-9',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-savings',
      date: DateTime.now().subtract(const Duration(days: 2, hours: 8)),
      amountCents: 3200,
      currency: 'USD',
      category: 'Interest',
      createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 8)),
      rawText: 'Monthly savings interest',
      type: 'income',
      isRecurring: true,
    ),
    ExpenseEntry(
      id: 'preview-expense-10',
      contactId: contact.id,
      userId: contact.userId,
      householdId: null,
      date: DateTime.now().subtract(const Duration(days: 2, hours: 10)),
      amountCents: 7800,
      currency: 'USD',
      category: 'Groceries',
      createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 10)),
      rawText: 'Warehouse club stock-up',
      breakdown: const ['Pantry', 'Bulk'],
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-11',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-house-1',
      date: DateTime.now().subtract(const Duration(days: 6)),
      amountCents: 12900,
      currency: 'USD',
      category: 'Housing',
      createdAt: DateTime.now().subtract(const Duration(days: 6, hours: 2)),
      rawText: 'Loft utilities + internet',
      type: 'expense',
      isRecurring: true,
    ),
    ExpenseEntry(
      id: 'preview-expense-12',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-card',
      date: DateTime.now().subtract(const Duration(hours: 2)),
      amountCents: 1450,
      currency: 'USD',
      category: 'Dining',
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      rawText: 'Date night sushi',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-13',
      contactId: contact.id,
      userId: contact.userId,
      householdId: null,
      date: DateTime.now().subtract(const Duration(days: 1, hours: 1)),
      amountCents: 2999,
      currency: 'USD',
      category: 'Shopping',
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 1)),
      rawText: 'Noise-cancelling earbuds',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-14',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-house-2',
      date: DateTime.now().subtract(const Duration(days: 1, hours: 4)),
      amountCents: 5400,
      currency: 'USD',
      category: 'Gifts',
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 4)),
      rawText: 'Bridal shower gift',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-15',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-savings',
      date: DateTime.now().subtract(const Duration(days: 2, hours: 2)),
      amountCents: 2500,
      currency: 'USD',
      category: 'Interest',
      createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 2)),
      rawText: 'Savings interest bonus',
      type: 'income',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-16',
      contactId: contact.id,
      userId: contact.userId,
      householdId: null,
      date: DateTime.now().subtract(const Duration(days: 2, hours: 12)),
      amountCents: 8900,
      currency: 'USD',
      category: 'Health',
      createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 12)),
      rawText: 'Annual physical co-pay + labs',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-17',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-house-1',
      date: DateTime.now().subtract(const Duration(days: 3)),
      amountCents: 2300,
      currency: 'USD',
      category: 'Groceries',
      createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 1)),
      rawText: 'Specialty bakery + produce',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-18',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-card',
      date: DateTime.now().subtract(const Duration(days: 3, hours: 2)),
      amountCents: 1199,
      currency: 'USD',
      category: 'Entertainment',
      createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 2)),
      rawText: 'Streaming + movie night snacks',
      type: 'expense',
      isRecurring: true,
    ),
    ExpenseEntry(
      id: 'preview-expense-19',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-house-2',
      date: DateTime.now().subtract(const Duration(days: 4)),
      amountCents: 6500,
      currency: 'USD',
      category: 'Travel',
      createdAt: DateTime.now().subtract(const Duration(days: 4, hours: 3)),
      rawText: 'Weekend getaway cabin deposit',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-20',
      contactId: contact.id,
      userId: contact.userId,
      householdId: null,
      date: DateTime.now().subtract(const Duration(days: 4, hours: 5)),
      amountCents: 4500,
      currency: 'USD',
      category: 'Education',
      createdAt: DateTime.now().subtract(const Duration(days: 4, hours: 5)),
      rawText: 'Online course subscription',
      type: 'expense',
      isRecurring: true,
    ),
    ExpenseEntry(
      id: 'preview-expense-21',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-card',
      date: DateTime.now().subtract(const Duration(days: 5)),
      amountCents: 3300,
      currency: 'USD',
      category: 'Transportation',
      createdAt: DateTime.now().subtract(const Duration(days: 5, hours: 2)),
      rawText: 'Gas + car wash',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-22',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-house-1',
      date: DateTime.now().subtract(const Duration(days: 6, hours: 1)),
      amountCents: 1800,
      currency: 'USD',
      category: 'Pets',
      createdAt: DateTime.now().subtract(const Duration(days: 6, hours: 1)),
      rawText: 'Grooming + treats',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-23',
      contactId: contact.id,
      userId: contact.userId,
      householdId: null,
      date: DateTime.now().subtract(const Duration(days: 6, hours: 3)),
      amountCents: 7200,
      currency: 'USD',
      category: 'Income',
      createdAt: DateTime.now().subtract(const Duration(days: 6, hours: 3)),
      rawText: 'Freelance UI polish sprint',
      type: 'income',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-24',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-savings',
      date: DateTime.now().subtract(const Duration(days: 7)),
      amountCents: 15000,
      currency: 'USD',
      category: 'Transfers',
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      rawText: 'Paycheck sweep to savings',
      type: 'expense',
      isRecurring: true,
    ),
    ExpenseEntry(
      id: 'preview-expense-25',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-card',
      date: DateTime.now().subtract(const Duration(days: 7, hours: 6)),
      amountCents: 950,
      currency: 'USD',
      category: 'Subscriptions',
      createdAt: DateTime.now().subtract(const Duration(days: 7, hours: 6)),
      rawText: 'Cloud storage + password manager',
      type: 'expense',
      isRecurring: true,
    ),
    ExpenseEntry(
      id: 'preview-expense-26',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-house-2',
      date: DateTime.now().subtract(const Duration(days: 8)),
      amountCents: 4100,
      currency: 'USD',
      category: 'Wellness',
      createdAt: DateTime.now().subtract(const Duration(days: 8, hours: 1)),
      rawText: 'Spa day for bridal party',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-27',
      contactId: contact.id,
      userId: contact.userId,
      householdId: null,
      date: DateTime.now().subtract(const Duration(days: 8, hours: 5)),
      amountCents: 2800,
      currency: 'USD',
      category: 'Income',
      createdAt: DateTime.now().subtract(const Duration(days: 8, hours: 5)),
      rawText: 'Referral bonus payout',
      type: 'income',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-28',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-house-1',
      date: DateTime.now().subtract(const Duration(days: 9)),
      amountCents: 5100,
      currency: 'USD',
      category: 'Dining',
      createdAt: DateTime.now().subtract(const Duration(days: 9, hours: 2)),
      rawText: 'Friendsgiving groceries',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-29',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-card',
      date: DateTime.now().subtract(const Duration(days: 9, hours: 4)),
      amountCents: 2150,
      currency: 'USD',
      category: 'Transportation',
      createdAt: DateTime.now().subtract(const Duration(days: 9, hours: 4)),
      rawText: 'Metro + rideshare credits',
      type: 'expense',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-30',
      contactId: contact.id,
      userId: contact.userId,
      householdId: 'preview-savings',
      date: DateTime.now().subtract(const Duration(days: 10)),
      amountCents: 8000,
      currency: 'USD',
      category: 'Income',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      rawText: 'Savings account promo credit',
      type: 'income',
      isRecurring: false,
    ),
    ExpenseEntry(
      id: 'preview-expense-31',
      contactId: contact.id,
      userId: contact.userId,
      householdId: null,
      date: DateTime.now().subtract(const Duration(days: 10, hours: 6)),
      amountCents: 3600,
      currency: 'USD',
      category: 'Childcare',
      createdAt: DateTime.now().subtract(const Duration(days: 10, hours: 6)),
      rawText: 'Babysitter weekend booking',
      type: 'expense',
      isRecurring: false,
    ),
  ];

  static final List<RecurringTransaction> _recurringTransactions = [
    RecurringTransaction(
      id: 'preview-recurring-1',
      userId: contact.userId,
      date: DateTime.now(),
      category: 'Salary',
      description: 'Salary – Product Design Retainer',
      amount: 1800.00,
      currency: 'USD',
      ownerType: 'me',
      privacyScope: 'full',
      householdId: null,
      payerUserId: null,
      splitGroupId: null,
      recurrenceRule: RecurrenceRule(
        frequency: 'monthly',
        anchorDate: DateTime(DateTime.now().year, DateTime.now().month, 15),
      ),
      type: 'income',
      attachments: const [],
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
    ),
    RecurringTransaction(
      id: 'preview-recurring-2',
      userId: contact.userId,
      date: DateTime.now(),
      category: 'Wellness',
      description: 'Yoga studio membership',
      amount: 35.00,
      currency: 'USD',
      ownerType: 'me',
      privacyScope: 'full',
      householdId: 'preview-house-1',
      payerUserId: null,
      splitGroupId: null,
      recurrenceRule: RecurrenceRule(
        frequency: 'monthly',
        anchorDate: DateTime(DateTime.now().year, DateTime.now().month, 4),
      ),
      type: 'expense',
      attachments: const [],
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
    ),
    RecurringTransaction(
      id: 'preview-recurring-3',
      userId: contact.userId,
      date: DateTime.now(),
      category: 'Debt Payments',
      description: 'Card payment — Sapphire',
      amount: 42.00,
      currency: 'USD',
      ownerType: 'me',
      privacyScope: 'full',
      householdId: 'preview-card',
      payerUserId: null,
      splitGroupId: null,
      recurrenceRule: RecurrenceRule(
        frequency: 'monthly',
        anchorDate: DateTime(DateTime.now().year, DateTime.now().month, 12),
      ),
      type: 'expense',
      attachments: const [],
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
    ),
    RecurringTransaction(
      id: 'preview-recurring-4',
      userId: contact.userId,
      date: DateTime.now(),
      category: 'Transfers',
      description: 'Savings auto-transfer',
      amount: 500.00,
      currency: 'USD',
      ownerType: 'me',
      privacyScope: 'full',
      householdId: 'preview-savings',
      payerUserId: null,
      splitGroupId: null,
      recurrenceRule: RecurrenceRule(
        frequency: 'biweekly',
        anchorDate: DateTime.now().subtract(const Duration(days: 7)),
      ),
      type: 'expense',
      attachments: const [],
      createdAt: DateTime.now().subtract(const Duration(days: 14)),
    ),
    RecurringTransaction(
      id: 'preview-recurring-5',
      userId: contact.userId,
      date: DateTime.now(),
      category: 'Entertainment',
      description: 'Streaming bundle',
      amount: 18.99,
      currency: 'USD',
      ownerType: 'me',
      privacyScope: 'full',
      householdId: null,
      payerUserId: null,
      splitGroupId: null,
      recurrenceRule: RecurrenceRule(
        frequency: 'monthly',
        anchorDate: DateTime(DateTime.now().year, DateTime.now().month, 5),
      ),
      type: 'expense',
      attachments: const [],
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
    ),
    RecurringTransaction(
      id: 'preview-recurring-6',
      userId: contact.userId,
      date: DateTime.now(),
      category: 'Housing',
      description: 'Roomies utilities',
      amount: 129.00,
      currency: 'USD',
      ownerType: 'me',
      privacyScope: 'full',
      householdId: 'preview-house-1',
      payerUserId: null,
      splitGroupId: null,
      recurrenceRule: RecurrenceRule(
        frequency: 'monthly',
        anchorDate: DateTime(DateTime.now().year, DateTime.now().month, 18),
      ),
      type: 'expense',
      attachments: const [],
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
    ),
    RecurringTransaction(
      id: 'preview-recurring-7',
      userId: contact.userId,
      date: DateTime.now(),
      category: 'Transfers',
      description: 'Wedding savings',
      amount: 150.00,
      currency: 'USD',
      ownerType: 'me',
      privacyScope: 'full',
      householdId: 'preview-house-2',
      payerUserId: null,
      splitGroupId: null,
      recurrenceRule: RecurrenceRule(
        frequency: 'monthly',
        anchorDate: DateTime(DateTime.now().year, DateTime.now().month, 1),
      ),
      type: 'expense',
      attachments: const [],
      createdAt: DateTime.now().subtract(const Duration(days: 120)),
    ),
    RecurringTransaction(
      id: 'preview-recurring-8',
      userId: contact.userId,
      date: DateTime.now(),
      category: 'Salary',
      description: 'Design retainer',
      amount: 4200.00,
      currency: 'USD',
      ownerType: 'me',
      privacyScope: 'full',
      householdId: null,
      payerUserId: null,
      splitGroupId: null,
      recurrenceRule: RecurrenceRule(
        frequency: 'monthly',
        anchorDate: DateTime(DateTime.now().year, DateTime.now().month, 15),
      ),
      type: 'income',
      attachments: const [],
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
    ),
    RecurringTransaction(
      id: 'preview-recurring-9',
      userId: contact.userId,
      date: DateTime.now(),
      category: 'Wellness',
      description: 'Gym membership',
      amount: 35.00,
      currency: 'USD',
      ownerType: 'me',
      privacyScope: 'full',
      householdId: 'preview-card',
      payerUserId: null,
      splitGroupId: null,
      recurrenceRule: RecurrenceRule(
        frequency: 'monthly',
        anchorDate: DateTime(DateTime.now().year, DateTime.now().month, 3),
      ),
      type: 'expense',
      attachments: const [],
      createdAt: DateTime.now().subtract(const Duration(days: 45)),
    ),
    RecurringTransaction(
      id: 'preview-recurring-10',
      userId: contact.userId,
      date: DateTime.now(),
      category: 'Interest',
      description: 'Savings interest credit',
      amount: 32.00,
      currency: 'USD',
      ownerType: 'me',
      privacyScope: 'full',
      householdId: 'preview-savings',
      payerUserId: null,
      splitGroupId: null,
      recurrenceRule: RecurrenceRule(
        frequency: 'monthly',
        anchorDate: DateTime(DateTime.now().year, DateTime.now().month, 28),
      ),
      type: 'income',
      attachments: const [],
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
    ),
  ];

  static final List<DailyBudgetEntry> _budgets = [
    DailyBudgetEntry(
      id: 'preview-budget-1',
      contactId: contact.id,
      date: DateTime.now(),
      amountCents: 1200,
      currency: 'USD',
    ),
    DailyBudgetEntry(
      id: 'preview-budget-2',
      contactId: contact.id,
      date: DateTime.now().add(const Duration(days: 1)),
      amountCents: 1200,
      currency: 'USD',
    ),
    DailyBudgetEntry(
      id: 'preview-budget-3',
      contactId: contact.id,
      date: DateTime.now().add(const Duration(days: 2)),
      amountCents: 1400,
      currency: 'USD',
    ),
  ];

  static final List<PocketEnvelope> _pockets = [
    PocketEnvelope(
      id: 'preview-pocket-1',
      name: 'Living Essentials',
      budgetAmountCents: 40000,
      spent: 310.0,
      currency: 'USD',
      icon: 'home',
      color: '#FF2D55',
      budgetId: 'preview-budget-main',
      householdId: 'preview-house-1',
      lastUpdated: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    PocketEnvelope(
      id: 'preview-pocket-2',
      name: 'Eating Out',
      budgetAmountCents: 18000,
      spent: 95.5,
      currency: 'USD',
      icon: 'restaurant',
      color: '#AF52DE',
      budgetId: 'preview-budget-main',
      householdId: 'preview-house-1',
      lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
    ),
    PocketEnvelope(
      id: 'preview-pocket-3',
      name: 'Wellness',
      budgetAmountCents: 12000,
      spent: 45.0,
      currency: 'USD',
      icon: 'spa',
      color: '#FF9500',
      budgetId: 'preview-budget-main',
      householdId: 'preview-house-2',
      lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
    ),
  ];

  static final List<Household> _households = [
    Household(
      id: 'preview-house-1',
      name: 'Roomies Loft',
      currency: 'USD',
      coverImageUrl: null,
      themeColor: '#F97316',
      createdAt: DateTime.now().subtract(const Duration(days: 120)),
      updatedAt: DateTime.now(),
      ownerId: contact.userId ?? 'preview-user',
      isPortfolio: false,
    ),
    Household(
      id: 'preview-house-2',
      name: 'Wedding Fund',
      currency: 'USD',
      coverImageUrl: null,
      themeColor: '#6366F1',
      createdAt: DateTime.now().subtract(const Duration(days: 240)),
      updatedAt: DateTime.now(),
      ownerId: contact.userId ?? 'preview-user',
      isPortfolio: false,
    ),
    Household(
      id: 'preview-card',
      name: 'Chase Sapphire',
      currency: 'USD',
      coverImageUrl: null,
      themeColor: '#0EA5E9',
      createdAt: DateTime.now().subtract(const Duration(days: 45)),
      updatedAt: DateTime.now(),
      ownerId: contact.userId ?? 'preview-user',
      isPortfolio: true,
    ),
    Household(
      id: 'preview-savings',
      name: 'High-Yield Savings',
      currency: 'USD',
      coverImageUrl: null,
      themeColor: '#10B981',
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
      updatedAt: DateTime.now(),
      ownerId: contact.userId ?? 'preview-user',
      isPortfolio: true,
    ),
  ];

  static final List<WalletEntity> _wallets = [
    WalletEntity(
      id: 'preview-spending',
      userId: contact.userId ?? 'preview-user',
      householdId: null,
      name: 'Everyday Spending',
      icon: 'wallet',
      color: '#F9A8D4',
      currency: 'USD',
      openingBalanceCents: 235000,
      goalAmountCents: null,
      isDefault: true,
      isSystem: true,
      isArchived: false,
      currentBalanceCents: 235000,
    ),
    WalletEntity(
      id: 'preview-house-1',
      userId: contact.userId ?? 'preview-user',
      householdId: 'preview-house-1',
      name: 'Loft Shared Spending',
      icon: 'groups',
      color: '#F97316',
      currency: 'USD',
      openingBalanceCents: 164000,
      goalAmountCents: null,
      isDefault: false,
      isSystem: false,
      isArchived: false,
      currentBalanceCents: 164000,
    ),
    WalletEntity(
      id: 'preview-house-2',
      userId: contact.userId ?? 'preview-user',
      householdId: 'preview-house-2',
      name: 'Wedding Fund Cash',
      icon: 'favorite',
      color: '#6366F1',
      currency: 'USD',
      openingBalanceCents: 420000,
      goalAmountCents: 750000,
      isDefault: false,
      isSystem: false,
      isArchived: false,
      currentBalanceCents: 420000,
    ),
    WalletEntity(
      id: 'preview-card',
      userId: contact.userId ?? 'preview-user',
      householdId: 'preview-card',
      name: 'Chase Sapphire',
      icon: 'credit_card',
      color: '#0EA5E9',
      currency: 'USD',
      openingBalanceCents: -32000,
      goalAmountCents: null,
      isDefault: false,
      isSystem: false,
      isArchived: false,
      currentBalanceCents: -32000,
    ),
    WalletEntity(
      id: 'preview-savings',
      userId: contact.userId ?? 'preview-user',
      householdId: 'preview-savings',
      name: 'High-Yield Savings',
      icon: 'savings',
      color: '#10B981',
      currency: 'USD',
      openingBalanceCents: 850000,
      goalAmountCents: 1000000,
      isDefault: false,
      isSystem: false,
      isArchived: false,
      currentBalanceCents: 850000,
    ),
  ];

  static Household _copyHousehold(Household household) {
    return Household(
      id: household.id,
      name: household.name,
      currency: household.currency,
      coverImageUrl: household.coverImageUrl,
      themeColor: household.themeColor,
      createdAt: household.createdAt,
      updatedAt: household.updatedAt,
      ownerId: household.ownerId,
      isPortfolio: household.isPortfolio,
    );
  }

  static PocketEnvelope _copyPocket(PocketEnvelope pocket) {
    return PocketEnvelope(
      id: pocket.id,
      name: pocket.name,
      budgetAmountCents: pocket.budgetAmountCents,
      spent: pocket.spent,
      currency: pocket.currency,
      icon: pocket.icon,
      color: pocket.color,
      budgetId: pocket.budgetId,
      householdId: pocket.householdId,
      lastUpdated: pocket.lastUpdated,
    );
  }

  static RecurringTransaction _copyRecurring(RecurringTransaction tx) {
    return RecurringTransaction(
      id: tx.id,
      userId: tx.userId,
      date: tx.date,
      category: tx.category,
      description: tx.description,
      source: tx.source,
      amount: tx.amount,
      currency: tx.currency,
      ownerType: tx.ownerType,
      privacyScope: tx.privacyScope,
      householdId: tx.householdId,
      payerUserId: tx.payerUserId,
      splitGroupId: tx.splitGroupId,
      recurrenceRule: tx.recurrenceRule,
      type: tx.type,
      attachments: tx.attachments,
      createdAt: tx.createdAt,
      updatedAt: tx.updatedAt,
    );
  }

  static WalletEntity _copyWallet(WalletEntity wallet) {
    return WalletEntity(
      id: wallet.id,
      userId: wallet.userId,
      householdId: wallet.householdId,
      name: wallet.name,
      icon: wallet.icon,
      color: wallet.color,
      currency: wallet.currency,
      openingBalanceCents: wallet.openingBalanceCents,
      goalAmountCents: wallet.goalAmountCents,
      isDefault: wallet.isDefault,
      isSystem: wallet.isSystem,
      isArchived: wallet.isArchived,
      currentBalanceCents: wallet.currentBalanceCents,
    );
  }
}
