/// Currency flag utilities for mapping currency codes to flag image assets
library;

/// Maps currency codes to flag image paths
/// Returns the asset path for the flag image or null if not available
String? getCurrencyFlagPath(String currencyCode) {
  final code = currencyCode.toUpperCase();
  const flagMap = {
    'USD': 'us',
    'EUR': 'europe',
    'GBP': 'uk',
    'ARS': 'argentina',
    'AUD': 'au',
    'BDT': 'bangladesh',
    'BZD': 'belize',
    'CAD': 'ca',
    'CNY': 'cn',
    'COP': 'colombia',
    'JPY': 'jp',
    'JMD': 'jamaica',
    'HKD': 'hk',
    'MOP': 'macau',
    'ILS': 'israel',
    'SGD': 'sg',
    'NZD': 'nz',
    'CZK': 'cz',
    'CHF': 'switzerland',
    'KRW': 'kr',
    'INR': 'india',
    'RUB': 'russia',
    'BRL': 'brazil',
    'MXN': 'mexico',
    'ZAR': 'south_africa',
    'SEK': 'sweden',
    'NOK': 'norway',
    'DKK': 'denmark',
    'NGN': 'nigeria',
    'PKR': 'pakistan',
    'KES': 'kenya',
    'GHS': 'ghana',
    'NPR': 'nepal',
    'PLN': 'poland',
    'RON': 'romania',
    'THB': 'thailand',
    'TWD': 'taiwan',
    'IDR': 'indonesia',
    'MYR': 'my',
    'MWK': 'malawi',
    'PHP': 'philippines',
    'PEN': 'peru',
    'TRY': 'turkey',
    'AED': 'uae',
    'SAR': 'saudi_arabia',
    'EGP': 'egypt',
    'ETB': 'ethiopia',
    'VND': 'vietnam',
    'DOP': 'dominican',
    'DZD': 'algeria',
    'PYG': 'paraguay',
    'UAH': 'ukraine',
    'LKR': 'sri_lanka',
    'GTQ': 'guatemala',
    'CLP': 'chile',
    'RSD': 'serbia',
    'HUF': 'hungary',
    'MMK': 'myanmar',
    'JOD': 'jordan',
    'SYP': 'syria',
    'ZMW': 'zambia',
    'XOF': 'senegal',
    'CRC': 'costa_rica',
    'XAF': 'cameroon',
  };

  final flagName = flagMap[code];
  return flagName != null ? 'lib/assets/images/flags/$flagName.png' : null;
}
