const Map<String, String> currencyDisplayNames = {
  'USD': 'United States Dollar',
  'EUR': 'Euro',
  'GBP': 'British Pound',
  'JPY': 'Japanese Yen',
  'CAD': 'Canadian Dollar',
  'AUD': 'Australian Dollar',
  'CNY': 'Chinese Yuan',
  'CHF': 'Swiss Franc',
  'HKD': 'Hong Kong Dollar',
  'SGD': 'Singapore Dollar',
  'NZD': 'New Zealand Dollar',
  'INR': 'Indian Rupee',
  'MXN': 'Mexican Peso',
  'BRL': 'Brazilian Real',
  'ZAR': 'South African Rand',
  'IDR': 'Indonesian Rupiah',
  'AED': 'United Arab Emirates Dirham',
  'SAR': 'Saudi Riyal',
  'TRY': 'Turkish Lira',
  'RUB': 'Russian Ruble',
  'KRW': 'South Korean Won',
  'PLN': 'Polish Zloty',
  'THB': 'Thai Baht',
  'MYR': 'Malaysian Ringgit',
  'PHP': 'Philippine Peso',
  'VND': 'Vietnamese Dong',
  'DKK': 'Danish Krone',
  'NOK': 'Norwegian Krone',
  'SEK': 'Swedish Krona',
  'EGP': 'Egyptian Pound',
  'ILS': 'Israeli New Shekel',
  'CLP': 'Chilean Peso',
  'COP': 'Colombian Peso',
  'DOP': 'Dominican Peso',
  'CZK': 'Czech Koruna',
  'BDT': 'Bangladeshi Taka',
  'BZD': 'Belize Dollar',
  'DZD': 'Algerian Dinar',
  'ETB': 'Ethiopian Birr',
  'GHS': 'Ghanaian Cedi',
  'GTQ': 'Guatemalan Quetzal',
  'HUF': 'Hungarian Forint',
  'JMD': 'Jamaican Dollar',
  'KES': 'Kenyan Shilling',
  'LKR': 'Sri Lankan Rupee',
  'MWK': 'Malawian Kwacha',
  'NGN': 'Nigerian Naira',
  'NPR': 'Nepalese Rupee',
  'PEN': 'Peruvian Sol',
  'PKR': 'Pakistani Rupee',
  'PYG': 'Paraguayan Guarani',
  'RSD': 'Serbian Dinar',
  'RON': 'Romanian Leu',
  'UAH': 'Ukrainian Hryvnia',
  'ZMW': 'Zambian Kwacha',
  'XOF': 'West African CFA Franc',
  'CRC': 'Costa Rican Colon',
  'XAF': 'Central African CFA Franc',
};

String resolveCurrencyDisplayName(String code) {
  return currencyDisplayNames[code] ?? code;
}
