import 'package:moneko/shared/widgets/wallet_pocket_icon.dart';

export 'package:moneko/shared/widgets/wallet_pocket_icon.dart';

/// Shared constants for pocket/envelope icons
/// This ensures consistency across the app when displaying pocket icons
final pocketIconNames = uniqueWalletPocketIconNames(const [
  'account_balance',
  'account_balance_wallet',
  'apartment',
  'backpack',
  'bolt',
  'build_circle',
  'celebration',
  'child_care',
  'child_friendly',
  'cleaning_services',
  'coffee',
  'delete_outline',
  'diamond',
  'shopping_bag',
  'restaurant',
  'directions_car',
  'home',
  'house',
  'house_siding',
  'flight',
  'flight_takeoff',
  'fastfood',
  'favorite',
  'healing',
  'hotel',
  'inventory_2',
  'kitchen',
  'local_grocery_store',
  'map',
  'medical_services',
  'people',
  'policy',
  'priority_high',
  'ramen_dining',
  'receipt_long',
  'school',
  'pets',
  'sports_esports',
  'sports_soccer',
  'fitness_center',
  'local_cafe',
  'local_bar',
  'movie',
  'music_note',
  'self_improvement',
  'shield',
  'soap',
  'spa',
  'savings',
  'trending_up',
  'weekend',
  'wifi',
  'work',
], fallback: 'budget');
