// File generated by FlutterFire CLI.
// DO NOT MANUALLY EDIT THIS FILE
//
// To generate this file, run:
// flutterfire configure --project=moneko-app
//
// This will create platform-specific Firebase configuration files:
// - ios/Runner/GoogleService-Info.plist
// - android/app/google-services.json
// - lib/firebase_options.dart (this file)
//
// Make sure you have:
// 1. Installed FlutterFire CLI: `dart pub global activate flutterfire_cli`
// 2. Logged into Firebase: `firebase login`
// 3. Run the configuration command above

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Run: flutterfire configure --project=moneko-app

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlMgs8Go1eSElacNxrlDRx_FrhLKGzh_g',
    appId: '1:1075784863194:web:186cddfc395499032ec4e3',
    messagingSenderId: '1075784863194',
    projectId: 'paw-fi-3c4f7',
    authDomain: 'paw-fi-3c4f7.firebaseapp.com',
    storageBucket: 'paw-fi-3c4f7.firebasestorage.app',
    measurementId: 'G-QVWLQXNE8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdj_ndP9X4onSi-TPEamAuONLhxC94IaQ',
    appId: '1:1075784863194:android:bcb22b4dc8b0e8962ec4e3',
    messagingSenderId: '1075784863194',
    projectId: 'paw-fi-3c4f7',
    storageBucket: 'paw-fi-3c4f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuXW-0r1z7_eOHnoSMZZHJArQUsodrYwM',
    appId: '1:1075784863194:ios:5d785653675dce8e2ec4e3',
    messagingSenderId: '1075784863194',
    projectId: 'paw-fi-3c4f7',
    storageBucket: 'paw-fi-3c4f7.firebasestorage.app',
    iosBundleId: 'com.moneko.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'moneko-app',
    storageBucket: 'moneko-app.appspot.com',
    iosBundleId: 'io.moneko.app',
  );
}