// Uses the image decoder already present in the locked dependency graph.
// ignore_for_file: depend_on_referenced_packages

import 'dart:io';
import 'dart:math' as math;
import 'package:image/image.dart' as image;

({double extent, double x, double y}) measure(String path) {
  final decoded = image.decodeImage(File(path).readAsBytesSync())!;
  var left = decoded.width;
  var top = decoded.height;
  var right = -1;
  var bottom = -1;
  for (final pixel in decoded) {
    // Ignore faint shadows when measuring the visible artwork.
    if (pixel.a / pixel.maxChannelValue < 0.125) continue;
    left = math.min(left, pixel.x);
    top = math.min(top, pixel.y);
    right = math.max(right, pixel.x);
    bottom = math.max(bottom, pixel.y);
  }
  if (right < left || bottom < top) throw StateError('Empty icon: $path');
  final basis = math.max(decoded.width, decoded.height);
  return (
    extent: math.max(right - left + 1, bottom - top + 1) / basis,
    x: ((left + right + 1) / 2 - decoded.width / 2) / basis,
    y: ((top + bottom + 1) / 2 - decoded.height / 2) / basis,
  );
}

void main() {
  const reference = 'lib/assets/images/wallet-pockets/house.png';
  final target = measure(reference);
  final files = [
    for (final directory in ['category', 'wallet-pockets'])
      ...Directory('lib/assets/images/$directory')
          .listSync(recursive: true)
          .whereType<File>()
          .where((file) => file.path.endsWith('.png')),
  ]..sort((a, b) => a.path.compareTo(b.path));
  final output = StringBuffer()
    ..writeln('// Generated by tool/generate_bundled_icon_metrics.dart.')
    ..writeln('// PNG alpha bounds reference: wallet-pockets/house.png.')
    ..writeln(
        '// Values are scale and center offsets relative to the requested icon size.')
    ..writeln('const bundledIconMetrics = <String, (double, double, double)>{');
  for (final file in files) {
    final bounds = measure(file.path);
    final scale = target.extent / bounds.extent;
    final x = target.x - bounds.x * scale;
    final y = target.y - bounds.y * scale;
    output.writeln(
        "  '${file.path}': (${scale.toStringAsFixed(6)}, ${x.toStringAsFixed(6)}, ${y.toStringAsFixed(6)}),");
    if (file.path == reference ||
        file.path.endsWith('/restaurants.png') ||
        file.path.endsWith('/spa-massage.png')) {
      stdout.writeln(
          '${file.path}: visible=${bounds.extent.toStringAsFixed(3)}, scale=${scale.toStringAsFixed(3)}');
    }
  }
  output.writeln('};');
  File('lib/shared/widgets/bundled_icon_metrics.dart')
      .writeAsStringSync(output.toString());
  stdout.writeln(
      'Measured ${files.length} bundled icons. Reference extent: ${target.extent.toStringAsFixed(3)}.');
}
