const List<String> householdNotificationSupportedEvents = <String>[
  'expense_added',
  'expense_edited',
  'expense_deleted',
  'income_added',
  'income_edited',
  'budget_warn',
  'budget_alert',
  'split_created',
  'split_settled',
  'settlement_completed',
  'invite_accepted',
  'member_joined',
  'member_left',
  'member_removed',
  'member_reminded',
  'invite_reminder_inviter',
  'invite_reminder_invitee',
  'recurring_reminder',
  'log_expense_reminder',
];

const Map<String, String> householdNotificationDefaultAction = <String, String>{
  'expense_added': 'open_expense_sheet',
  'expense_edited': 'open_expense_sheet',
  'expense_deleted': 'open_household_dashboard',
  'income_added': 'open_expense_sheet',
  'income_edited': 'open_expense_sheet',
  'budget_warn': 'open_budget_status',
  'budget_alert': 'open_budget_status',
  'split_created': 'open_expense_sheet',
  'split_settled': 'open_settlement_history',
  'settlement_completed': 'open_settlement_history',
  'invite_accepted': 'open_household_dashboard',
  'member_joined': 'open_household_dashboard',
  'member_left': 'open_household_dashboard',
  'member_removed': 'open_household_dashboard',
  'member_reminded': 'open_household_dashboard',
  'invite_reminder_inviter': 'open_household_invites',
  'invite_reminder_invitee': 'open_household_invitation_sheet',
  'recurring_reminder': 'open_recurring_editor',
  'log_expense_reminder': 'open_log_expense_quick_entry',
};
