// Generated by tool/generate_bundled_icon_metrics.dart.
// PNG alpha bounds reference: wallet-pockets/house.png.
// Values are scale and center offsets relative to the requested icon size.
const bundledIconMetrics = <String, (double, double, double)>{
  'lib/assets/images/category/apartment.png': (1.228070, -0.003598, -0.011993),
  'lib/assets/images/category/baby.png': (1.196581, 0.014022, 0.012854),
  'lib/assets/images/category/bank.png': (1.242604, -0.019416, 0.038831),
  'lib/assets/images/category/bill.png': (1.242604, -0.019416, -0.021843),
  'lib/assets/images/category/bolt.png': (1.228070, -0.001199, -0.050370),
  'lib/assets/images/category/book.png': (1.238938, 0.001210, -0.001210),
  'lib/assets/images/category/bus.png': (1.246291, 0.001217, -0.001217),
  'lib/assets/images/category/business.png': (1.253731, -0.001224, -0.001224),
  'lib/assets/images/category/car.png': (1.246291, 0.001217, 0.001217),
  'lib/assets/images/category/card.png': (1.265060, 0.002471, 0.002471),
  'lib/assets/images/category/cart.png': (1.228070, 0.025185, 0.023986),
  'lib/assets/images/category/chair.png': (1.228070, 0.026384, -0.013192),
  'lib/assets/images/category/chart.png': (1.272727, 0.000000, 0.002486),
  'lib/assets/images/category/child.png': (1.193182, -0.011652, 0.013983),
  'lib/assets/images/category/cleaning.png': (1.228070, -0.005996, 0.011993),
  'lib/assets/images/category/coffee.png': (1.228070, -0.040776, -0.011993),
  'lib/assets/images/category/community-misc/community-events.png': (
    1.242604,
    -0.014562,
    0.037618
  ),
  'lib/assets/images/category/community-misc/environmental-green.png': (
    1.238938,
    -0.018149,
    0.004840
  ),
  'lib/assets/images/category/community-misc/government-services.png': (
    1.235294,
    0.013270,
    0.074793
  ),
  'lib/assets/images/category/community-misc/miscellaneous.png': (
    1.238938,
    0.001210,
    0.015729
  ),
  'lib/assets/images/category/community-misc/other.png': (
    1.261261,
    0.001232,
    0.003695
  ),
  'lib/assets/images/category/community-misc/post-delivery.png': (
    1.238938,
    0.018149,
    0.000000
  ),
  'lib/assets/images/category/community-misc/religious-spiritual.png': (
    1.238938,
    0.001210,
    0.098002
  ),
  'lib/assets/images/category/community-misc/uncategorized.png': (
    1.265060,
    0.000000,
    -0.002471
  ),
  'lib/assets/images/category/delivery.png': (1.228070, 0.001199, 0.016790),
  'lib/assets/images/category/fitness.png': (1.200000, 0.000000, 0.002344),
  'lib/assets/images/category/food.png': (1.228070, 0.016790, 0.064762),
  'lib/assets/images/category/fun-social/bars-drinks.png': (
    1.250000,
    -0.048828,
    -0.070801
  ),
  'lib/assets/images/category/fun-social/charity.png': (
    1.253731,
    -0.001224,
    0.063666
  ),
  'lib/assets/images/category/fun-social/collectibles.png': (
    1.257485,
    0.000000,
    0.002456
  ),
  'lib/assets/images/category/fun-social/concerts-events.png': (
    1.246291,
    0.001217,
    0.010954
  ),
  'lib/assets/images/category/fun-social/crafts-art.png': (
    1.246291,
    0.018256,
    0.000000
  ),
  'lib/assets/images/category/fun-social/dating.png': (
    1.250000,
    0.007324,
    0.002441
  ),
  'lib/assets/images/category/fun-social/games-apps.png': (
    1.250000,
    0.021973,
    -0.014648
  ),
  'lib/assets/images/category/fun-social/gifts.png': (
    1.246291,
    0.000000,
    0.008520
  ),
  'lib/assets/images/category/fun-social/hobbies.png': (
    1.250000,
    0.007324,
    0.029297
  ),
  'lib/assets/images/category/fun-social/movies-shows.png': (
    1.253731,
    -0.008570,
    -0.001224
  ),
  'lib/assets/images/category/fun-social/music-streaming.png': (
    1.250000,
    0.007324,
    0.026855
  ),
  'lib/assets/images/category/fun-social/parties-hosting.png': (
    1.253731,
    -0.024487,
    0.013468
  ),
  'lib/assets/images/category/fun-social/sports-clubs.png': (
    1.250000,
    -0.007324,
    -0.003662
  ),
  'lib/assets/images/category/game.png': (1.250000, 0.021973, -0.014648),
  'lib/assets/images/category/gas.png': (1.253731, 0.001224, 0.000000),
  'lib/assets/images/category/grocery.png': (1.228070, 0.025185, 0.023986),
  'lib/assets/images/category/health-wellness/beauty-cosmetics.png': (
    1.196581,
    -0.005843,
    0.012854
  ),
  'lib/assets/images/category/health-wellness/dental-care.png': (
    1.196581,
    -0.010517,
    -0.011685
  ),
  'lib/assets/images/category/health-wellness/eye-care.png': (
    1.196581,
    -0.008180,
    0.012854
  ),
  'lib/assets/images/category/health-wellness/fitness-gym.png': (
    1.200000,
    0.000000,
    0.002344
  ),
  'lib/assets/images/category/health-wellness/medical-care.png': (
    1.196581,
    -0.001169,
    0.011685
  ),
  'lib/assets/images/category/health-wellness/mental-health.png': (
    1.189802,
    0.011619,
    -0.008133
  ),
  'lib/assets/images/category/health-wellness/personal-care.png': (
    1.200000,
    0.005859,
    0.016406
  ),
  'lib/assets/images/category/health-wellness/pharmacy.png': (
    1.193182,
    -0.010487,
    0.011652
  ),
  'lib/assets/images/category/health-wellness/spa-massage.png': (
    1.193182,
    -0.006991,
    0.012817
  ),
  'lib/assets/images/category/health-wellness/sports-exercise.png': (
    1.196581,
    0.012854,
    0.012854
  ),
  'lib/assets/images/category/health-wellness/supplements.png': (
    1.200000,
    -0.011719,
    0.011719
  ),
  'lib/assets/images/category/health-wellness/therapy.png': (
    1.242604,
    -0.021843,
    -0.004854
  ),
  'lib/assets/images/category/health.png': (1.196581, -0.001169, 0.011685),
  'lib/assets/images/category/help.png': (1.265060, 0.000000, -0.002471),
  'lib/assets/images/category/home-utilities/electricity.png': (
    1.228070,
    -0.001199,
    -0.050370
  ),
  'lib/assets/images/category/home-utilities/health-insurance.png': (
    1.228070,
    -0.001199,
    -0.014391
  ),
  'lib/assets/images/category/home-utilities/heating-gas.png': (
    1.228070,
    0.004797,
    0.064762
  ),
  'lib/assets/images/category/home-utilities/home-decor.png': (
    1.228070,
    0.000000,
    -0.023986
  ),
  'lib/assets/images/category/home-utilities/home-insurance.png': (
    1.228070,
    -0.003598,
    -0.011993
  ),
  'lib/assets/images/category/home-utilities/home-security.png': (
    1.257485,
    0.002456,
    0.003684
  ),
  'lib/assets/images/category/home-utilities/insurance.png': (
    1.228070,
    -0.001199,
    -0.014391
  ),
  'lib/assets/images/category/home-utilities/internet.png': (
    1.228070,
    0.002399,
    0.087548
  ),
  'lib/assets/images/category/home-utilities/life-insurance.png': (
    1.228070,
    -0.003598,
    -0.014391
  ),
  'lib/assets/images/category/home-utilities/mortgage.png': (
    1.231672,
    0.018042,
    0.021650
  ),
  'lib/assets/images/category/home-utilities/phone-bill.png': (
    1.235294,
    -0.043428,
    0.007238
  ),
  'lib/assets/images/category/home-utilities/rent.png': (
    1.228070,
    0.000000,
    0.000000
  ),
  'lib/assets/images/category/home-utilities/renters-insurance.png': (
    1.228070,
    -0.003598,
    -0.011993
  ),
  'lib/assets/images/category/home-utilities/trash-recycling.png': (
    1.265060,
    -0.003706,
    0.000000
  ),
  'lib/assets/images/category/home-utilities/water.png': (
    1.231672,
    0.001203,
    0.054126
  ),
  'lib/assets/images/category/home.png': (1.228070, -0.003598, -0.011993),
  'lib/assets/images/category/hospital.png': (1.196581, -0.001169, 0.011685),
  'lib/assets/images/category/kids-pets/baby-supplies.png': (
    1.196581,
    0.014022,
    0.012854
  ),
  'lib/assets/images/category/kids-pets/childcare.png': (
    1.193182,
    -0.011652,
    0.013983
  ),
  'lib/assets/images/category/kids-pets/kids-activities.png': (
    1.341853,
    0.014414,
    -0.013104
  ),
  'lib/assets/images/category/kids-pets/kids-clothing.png': (
    1.193182,
    -0.002330,
    -0.009322
  ),
  'lib/assets/images/category/kids-pets/pet-boarding-sitting.png': (
    1.246291,
    -0.001217,
    0.001217
  ),
  'lib/assets/images/category/kids-pets/pet-food.png': (
    1.196581,
    0.001169,
    0.012854
  ),
  'lib/assets/images/category/kids-pets/pet-grooming.png': (
    1.189802,
    -0.008133,
    -0.006971
  ),
  'lib/assets/images/category/kids-pets/pet-insurance.png': (
    1.246291,
    0.000000,
    0.001217
  ),
  'lib/assets/images/category/kids-pets/pet-medicine.png': (
    1.193182,
    -0.010487,
    0.011652
  ),
  'lib/assets/images/category/kids-pets/pet-supplies.png': (
    1.193182,
    0.002330,
    0.010487
  ),
  'lib/assets/images/category/kids-pets/pet-treats.png': (
    1.200000,
    -0.002344,
    0.012891
  ),
  'lib/assets/images/category/kids-pets/school-supplies.png': (
    1.196581,
    -0.012854,
    0.009348
  ),
  'lib/assets/images/category/kids-pets/toys-games.png': (
    1.196581,
    -0.008180,
    0.010517
  ),
  'lib/assets/images/category/kids-pets/vet-visits.png': (
    1.200000,
    -0.011719,
    0.011719
  ),
  'lib/assets/images/category/kitchen.png': (1.228070, 0.000000, -0.014391),
  'lib/assets/images/category/laptop.png': (1.312500, 0.000000, 0.000000),
  'lib/assets/images/category/leaf.png': (1.238938, -0.018149, 0.004840),
  'lib/assets/images/category/life-home/appliances.png': (
    1.228070,
    0.000000,
    -0.014391
  ),
  'lib/assets/images/category/life-home/cleaning-supplies.png': (
    1.228070,
    -0.005996,
    0.011993
  ),
  'lib/assets/images/category/life-home/clothing-shoes.png': (
    1.261261,
    0.001232,
    0.002463
  ),
  'lib/assets/images/category/life-home/coffee-tea.png': (
    1.228070,
    -0.040776,
    -0.011993
  ),
  'lib/assets/images/category/life-home/food-drinks.png': (
    1.228070,
    0.016790,
    0.064762
  ),
  'lib/assets/images/category/life-home/furniture.png': (
    1.228070,
    0.026384,
    -0.013192
  ),
  'lib/assets/images/category/life-home/groceries.png': (
    1.228070,
    0.025185,
    0.023986
  ),
  'lib/assets/images/category/life-home/home-repairs.png': (
    1.228070,
    0.000000,
    -0.015591
  ),
  'lib/assets/images/category/life-home/home-services.png': (
    1.228070,
    0.000000,
    0.020388
  ),
  'lib/assets/images/category/life-home/household-supplies.png': (
    1.268882,
    -0.001239,
    0.000000
  ),
  'lib/assets/images/category/life-home/laundry-dry-cleaning.png': (
    1.268882,
    0.001239,
    -0.001239
  ),
  'lib/assets/images/category/life-home/moving-costs.png': (
    1.265060,
    0.002471,
    0.002471
  ),
  'lib/assets/images/category/life-home/restaurants.png': (
    1.228070,
    0.004797,
    0.003598
  ),
  'lib/assets/images/category/life-home/snacks.png': (
    1.228070,
    0.002399,
    0.014391
  ),
  'lib/assets/images/category/life-home/storage.png': (
    1.272727,
    0.000000,
    0.001243
  ),
  'lib/assets/images/category/life-home/takeout-delivery.png': (
    1.228070,
    0.001199,
    0.016790
  ),
  'lib/assets/images/category/medical.png': (1.196581, -0.001169, 0.011685),
  'lib/assets/images/category/money.png': (1.253731, -0.001224, -0.001224),
  'lib/assets/images/category/money/bank-fees.png': (
    1.242604,
    -0.019416,
    -0.021843
  ),
  'lib/assets/images/category/money/bonus.png': (1.257485, 0.000000, 0.002456),
  'lib/assets/images/category/money/cashback.png': (
    1.265060,
    0.002471,
    0.002471
  ),
  'lib/assets/images/category/money/debt-payments.png': (
    1.235294,
    -0.012063,
    0.014476
  ),
  'lib/assets/images/category/money/fines.png': (1.242604, -0.007281, 0.010921),
  'lib/assets/images/category/money/freelance-income.png': (
    1.268882,
    0.001239,
    0.001239
  ),
  'lib/assets/images/category/money/gift.png': (1.246291, 0.000000, 0.008520),
  'lib/assets/images/category/money/income.png': (
    1.253731,
    -0.001224,
    -0.001224
  ),
  'lib/assets/images/category/money/interest-income.png': (
    1.265060,
    0.001235,
    0.002471
  ),
  'lib/assets/images/category/money/investments.png': (
    1.272727,
    0.000000,
    0.002486
  ),
  'lib/assets/images/category/money/loan-payments.png': (
    1.235294,
    0.000000,
    0.039809
  ),
  'lib/assets/images/category/money/pension.png': (
    1.268882,
    -0.001239,
    0.002478
  ),
  'lib/assets/images/category/money/refunds.png': (
    1.265060,
    -0.002471,
    0.002471
  ),
  'lib/assets/images/category/money/rental-income.png': (
    1.265060,
    0.002471,
    0.001235
  ),
  'lib/assets/images/category/money/salary.png': (
    1.253731,
    -0.002449,
    -0.001224
  ),
  'lib/assets/images/category/money/savings.png': (
    1.242604,
    -0.019416,
    0.038831
  ),
  'lib/assets/images/category/money/taxes.png': (1.235294, -0.031365, 0.013270),
  'lib/assets/images/category/money/tips.png': (1.265060, 0.000000, 0.001235),
  'lib/assets/images/category/money/transfers.png': (
    1.265060,
    0.000000,
    0.002471
  ),
  'lib/assets/images/category/movie.png': (1.253731, -0.008570, -0.001224),
  'lib/assets/images/category/music.png': (1.250000, 0.007324, 0.026855),
  'lib/assets/images/category/party.png': (1.253731, -0.024487, 0.013468),
  'lib/assets/images/category/people.png': (1.242604, -0.014562, 0.037618),
  'lib/assets/images/category/pet.png': (1.246291, -0.001217, 0.001217),
  'lib/assets/images/category/phone.png': (1.235294, -0.043428, 0.007238),
  'lib/assets/images/category/plane.png': (1.193182, 0.002330, -0.011652),
  'lib/assets/images/category/restaurant.png': (1.228070, 0.004797, 0.003598),
  'lib/assets/images/category/school.png': (1.196581, -0.012854, 0.009348),
  'lib/assets/images/category/shield.png': (1.228070, -0.001199, -0.014391),
  'lib/assets/images/category/shopping.png': (1.228070, 0.025185, 0.023986),
  'lib/assets/images/category/spa.png': (1.193182, -0.006991, 0.012817),
  'lib/assets/images/category/star.png': (1.257485, 0.000000, 0.002456),
  'lib/assets/images/category/tag.png': (1.147541, -0.030257, -0.020172),
  'lib/assets/images/category/tools.png': (1.228070, 0.000000, -0.015591),
  'lib/assets/images/category/train.png': (1.246291, 0.002434, 0.001217),
  'lib/assets/images/category/transport/bike-scooter.png': (
    1.238938,
    0.001210,
    0.000000
  ),
  'lib/assets/images/category/transport/car-insurance.png': (
    1.253731,
    -0.001224,
    0.001224
  ),
  'lib/assets/images/category/transport/car-parts.png': (
    1.250000,
    0.000000,
    0.000000
  ),
  'lib/assets/images/category/transport/car-rental.png': (
    1.246291,
    0.001217,
    0.001217
  ),
  'lib/assets/images/category/transport/car-repairs.png': (
    1.242604,
    0.000000,
    0.001213
  ),
  'lib/assets/images/category/transport/fuel-gas.png': (
    1.253731,
    0.001224,
    0.000000
  ),
  'lib/assets/images/category/transport/parking.png': (
    1.246291,
    0.001217,
    0.000000
  ),
  'lib/assets/images/category/transport/public-transport.png': (
    1.246291,
    0.002434,
    0.001217
  ),
  'lib/assets/images/category/transport/taxi-ride-apps.png': (
    1.250000,
    0.002441,
    0.000000
  ),
  'lib/assets/images/category/transport/tolls.png': (
    1.246291,
    0.001217,
    0.001217
  ),
  'lib/assets/images/category/transport/transportation.png': (
    1.246291,
    0.001217,
    -0.001217
  ),
  'lib/assets/images/category/transport/travel.png': (
    1.250000,
    0.000000,
    0.000000
  ),
  'lib/assets/images/category/travel/flights.png': (
    1.193182,
    0.002330,
    -0.011652
  ),
  'lib/assets/images/category/travel/hotels.png': (
    1.193182,
    -0.011652,
    0.003496
  ),
  'lib/assets/images/category/travel/luggage-travel-gear.png': (
    1.196581,
    -0.010517,
    0.012854
  ),
  'lib/assets/images/category/travel/passport-visa-fees.png': (
    1.196581,
    -0.010517,
    0.011685
  ),
  'lib/assets/images/category/travel/transportation.png': (
    1.196581,
    -0.012854,
    0.015191
  ),
  'lib/assets/images/category/travel/travel-activities.png': (
    1.193182,
    0.002330,
    0.011652
  ),
  'lib/assets/images/category/travel/travel-insurance.png': (
    1.200000,
    0.000000,
    -0.009375
  ),
  'lib/assets/images/category/tv.png': (1.253731, -0.008570, -0.001224),
  'lib/assets/images/category/work-learning/ads-marketing.png': (
    1.272727,
    0.000000,
    -0.001243
  ),
  'lib/assets/images/category/work-learning/books-study-materials.png': (
    1.238938,
    0.001210,
    -0.001210
  ),
  'lib/assets/images/category/work-learning/business-expenses.png': (
    1.253731,
    -0.001224,
    -0.001224
  ),
  'lib/assets/images/category/work-learning/cloud-storage.png': (
    1.368078,
    0.001336,
    0.002672
  ),
  'lib/assets/images/category/work-learning/courses-classes.png': (
    1.350482,
    0.001319,
    0.000000
  ),
  'lib/assets/images/category/work-learning/coworking-space.png': (
    1.242604,
    0.000000,
    0.002427
  ),
  'lib/assets/images/category/work-learning/exams-certificates.png': (
    1.257485,
    0.000000,
    0.001228
  ),
  'lib/assets/images/category/work-learning/home-office.png': (
    1.312500,
    0.000000,
    0.000000
  ),
  'lib/assets/images/category/work-learning/licensing-fees.png': (
    1.253731,
    0.000000,
    0.001224
  ),
  'lib/assets/images/category/work-learning/professional-services.png': (
    1.250000,
    0.000000,
    0.000000
  ),
  'lib/assets/images/category/work-learning/software-tools.png': (
    1.253731,
    -0.001224,
    0.000000
  ),
  'lib/assets/images/category/work-learning/work-supplies.png': (
    1.250000,
    0.000000,
    0.002441
  ),
  'lib/assets/images/category/work.png': (1.250000, 0.000000, 0.002441),
  'lib/assets/images/wallet-pockets/account-balance-wallet.png': (
    1.014493,
    0.005944,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/account-balance.png': (
    1.014493,
    0.004954,
    0.005944
  ),
  'lib/assets/images/wallet-pockets/analytics.png': (
    1.004785,
    0.000000,
    0.000981
  ),
  'lib/assets/images/wallet-pockets/apartment.png': (
    1.000000,
    0.000000,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/backpack.png': (
    1.000000,
    0.000000,
    -0.000977
  ),
  'lib/assets/images/wallet-pockets/bank.png': (1.009615, 0.000000, 0.001972),
  'lib/assets/images/wallet-pockets/bills-financial-documents.png': (
    1.004785,
    0.000981,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/bills-receipts.png': (
    1.004785,
    0.000000,
    0.000981
  ),
  'lib/assets/images/wallet-pockets/budget.png': (1.004785, 0.000000, 0.000981),
  'lib/assets/images/wallet-pockets/business.png': (
    1.004785,
    0.000000,
    0.000981
  ),
  'lib/assets/images/wallet-pockets/cash-payments.png': (
    1.004785,
    0.000000,
    0.000981
  ),
  'lib/assets/images/wallet-pockets/cash.png': (1.004785, 0.000000, 0.000000),
  'lib/assets/images/wallet-pockets/category.png': (
    1.002387,
    0.000000,
    -0.000979
  ),
  'lib/assets/images/wallet-pockets/checking.png': (
    1.000000,
    0.000000,
    0.005859
  ),
  'lib/assets/images/wallet-pockets/child-care.png': (
    1.000000,
    0.005859,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/child-friendly.png': (
    1.000000,
    0.000977,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/credit-card.png': (
    1.004785,
    0.000000,
    0.000981
  ),
  'lib/assets/images/wallet-pockets/crypto.png': (1.007194, 0.000984, 0.000984),
  'lib/assets/images/wallet-pockets/custom-icon-image.png': (
    1.004785,
    0.000000,
    0.000981
  ),
  'lib/assets/images/wallet-pockets/debt.png': (1.000000, 0.000000, 0.000000),
  'lib/assets/images/wallet-pockets/diamond.png': (
    1.000000,
    0.000000,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/education.png': (
    1.004785,
    0.000000,
    0.000981
  ),
  'lib/assets/images/wallet-pockets/favorite.png': (
    1.000000,
    0.000000,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/flight-takeoff.png': (
    1.000000,
    0.000000,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/flight.png': (1.000000, 0.000000, 0.005859),
  'lib/assets/images/wallet-pockets/healing.png': (
    1.002387,
    0.000979,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/health-medical.png': (
    1.004785,
    0.000000,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/home.png': (1.004785, 0.000000, 0.000981),
  'lib/assets/images/wallet-pockets/house-siding.png': (
    1.012048,
    0.004942,
    0.003953
  ),
  'lib/assets/images/wallet-pockets/house.png': (1.000000, 0.000000, 0.000000),
  'lib/assets/images/wallet-pockets/insurance.png': (
    1.004785,
    0.000000,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/investments.png': (
    1.004785,
    0.000000,
    0.000981
  ),
  'lib/assets/images/wallet-pockets/kids-baby.png': (
    1.004785,
    0.000000,
    0.001962
  ),
  'lib/assets/images/wallet-pockets/local-cafe.png': (
    1.000000,
    0.000000,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/map.png': (1.000000, 0.000000, 0.000000),
  'lib/assets/images/wallet-pockets/medical-healthcare.png': (
    1.009615,
    0.000000,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/medical-services.png': (
    1.000000,
    0.006836,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/money-payments.png': (
    1.009615,
    0.000986,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/mortgage.png': (
    1.012048,
    0.004942,
    0.003953
  ),
  'lib/assets/images/wallet-pockets/people.png': (1.000000, 0.000000, 0.000000),
  'lib/assets/images/wallet-pockets/pet.png': (1.000000, 0.000000, 0.000000),
  'lib/assets/images/wallet-pockets/pets.png': (1.004785, 0.000000, 0.000000),
  'lib/assets/images/wallet-pockets/plane.png': (1.000000, 0.000000, 0.000000),
  'lib/assets/images/wallet-pockets/policy.png': (1.000000, 0.000000, 0.000000),
  'lib/assets/images/wallet-pockets/priority-high.png': (
    1.000000,
    0.000000,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/protected-secure.png': (
    1.004785,
    -0.000981,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/receipt-long.png': (
    1.000000,
    0.000000,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/retirement.png': (
    1.000000,
    0.000000,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/rewards.png': (
    1.004785,
    0.000981,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/savings.png': (
    1.004785,
    0.000000,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/school.png': (
    1.000000,
    0.000000,
    -0.000977
  ),
  'lib/assets/images/wallet-pockets/shared-family.png': (
    1.000000,
    0.000000,
    0.000977
  ),
  'lib/assets/images/wallet-pockets/shield.png': (1.000000, 0.000000, 0.000000),
  'lib/assets/images/wallet-pockets/trading.png': (
    1.009615,
    0.000986,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/travel.png': (
    1.002387,
    -0.000979,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/trending-up.png': (
    1.014493,
    0.005944,
    0.000000
  ),
  'lib/assets/images/wallet-pockets/wallet.png': (
    1.004785,
    0.000000,
    -0.000981
  ),
  'lib/assets/images/wallet-pockets/work.png': (1.000000, 0.000000, 0.000000),
};
